# Make sure this is set to "kotlinforforge"
modLoader="kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion="[3,)" # Require at least 3.x
# License is REQUIRED after 1.16
license='LGPL'

[[mods]]
modId="ptgt"
version="${file.jarVersion}"
displayName="Portal Gates"
credits="X'bao! Th'wgha! Chlamydomonos xia'd tschilhib'sgn!"
authors="Chlamydomonos"
description='''
A mod that adds electric portal gates to Minecraft.
Also adds a very bright light.
'''
[[dependencies.ptgt]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ptgt]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
